### ISSUE TITLE
Please explain in more detail what the plugin is doing

### ISSUE THREAD

**Issue by pcav** [sitnyon/qgis-plugin-settings-manager#43]
Is this of general use or specific to your infrastructure?
Are you aware of the work of @nathanW2 for a similar system in QGIS3?
Please write the about (also) in English, so more people will be able to understand it.

**Comment by rbovard** [comment]
> Is this of general use or specific to your infrastructure?

As written in the README, it's specific to our infrastructure https://github.com/sitnyon/qgis-plugin-settings-manager#features

> Are you aware of the work of @nathanW2 for a similar system in QGIS3?

No, could you please tell me more about?

> Please write the about (also) in English, so more people will be able to understand it.

Since it's specific to us, I do not think it's necessary. What do you think?

**Comment by NathanW2** [comment]
You can find more info here: https://github.com/qgis/QGIS/pull/4184

**Comment by pcav** [comment]
1. Please state it more clearly in the About
3. I think it's important, so more users will understand it's not useful, and developers may have a look for potentially interesting and generalizable stuff.
Thanks.

**Comment by rbovard** [comment]
> You can find more info here: qgis/QGIS#4184

Thanks @NathanW2, I'll will follow this major improvements.

**Comment by rbovard** [comment]
@pcav Did you notice this PR https://github.com/sitnyon/qgis-plugin-settings-manager/pull/44?
